### ISSUE TITLE
22.11.26 노영석 TODO

### ISSUE THREAD

**Issue by evelo0702** [BOOKPROJECT00/USED-BOOK#12]
kakaoLogin.vue  

- [x] 로그인 로그아웃 로직 처리

BookDetailView.vue 

- [ ] des 데이터 위치 변경
- [x] 베스트셀러 get 요청 

PaymentView.vue

- [x] 도로명주소-> 위도경도 (transLatLon 메소드 생성 )
- [x] 카카오 로컬 api 사용 

SearchView.vue

- [x] 성재님 파일과 합친후 생긴 오류 해결 
- [x] 책 데이터 가져오는 메소드 수정
- [x] 페이지네이션 메소드 수정  

Pagination.vue 

- [x] 페이지네이션 다음페이지 이전페이지 버튼 주석처리
