### ISSUE TITLE
곽성재 TODO

### ISSUE THREAD

**Issue by ssssssjay** [BOOKPROJECT00/USED-BOOK#7]
---
@ssssssjay TODO

- 검색어를 입력하고 제출(엔터 || 돋보기)하면, 쿼리값에 의거하여 결과 리스트 페이지로 이동하기 
    - [x] 기존의 `input`을 `form`으로 한번 감싸고 `submit`기능 추가 (BookSearchInput.vue)
    - [x] 돋보기 버튼을 클릭시 동일한 메소드를 거치도록 추가 (BookSearchInput.vue)
    - [x] `submit`함수에서 `router push`로 페이지 이동 (BookSearchInput.vue)
    - [x] 이동 시 `query: {q: value}`의 형태로 쿼리 값 넘기기 (BookSearchInput.vue)
    - [x] `searchView`에서 `useRoute import`해서 현재 주소에서 쿼리값 알아내기 (SearchView.vue)
    - [x] 알아낸 쿼리값으로 서버에 `get`요청 (SearchView.vue)
    - [x] 페이지 당 10개씩 렌더링 되므로 `cnt:10` 이라는 변수 추가 (SearchView.vue)
    - [x] 서버에서도 이 변수를 받을 수 있도록 코드 조정 (book.js_server)
    - [x] `this.booksForRender = result.data.item;` 로 데이터에 담아서 이 데이터에서 v-for로 렌더링 (SearchView.vue)

- 검색어 입력시 생성되는 검색리스트 클릭시 해당 책의 상세화면 페이지로 이동하기
    - [x] `li`태그에 클릭이벤트 바인딩 (BookSearchInput.vue)
    - [x] 클릭이벤트에 매개변수로 `book.isbn13`전달 (BookSearchInput.vue)
    - [x] `moveToBookDetail`함수에서 라우터로 페이지 이동 (BookSearchInput.vue)
    - [x] 이동 시 `query: {id: value}`의 형태로 쿼리 값 넘기기 (BookSearchInput.vue)
    - [x] `searchView`에서 `useRoute import`해서 현재 주소에서 쿼리값 알아내기 (BookDetailView.vue)
    - [x] 알아낸 쿼리값으로 서버에 `get`요청 (BookDetailView.vue)
    - [x] 서버에서 '상품 조회 API_알라딘'코드 추가 (book.js_server)
    - [x] `this.bookData = result.data.item[0];` 로 데이터에 담아서 이 데이터로 렌더링 (BookDetailView.vue)

- 중고책의 상세페이지에서 찜하기 기능 및 취소 기능 구현
    - [x]  클라이언트에서 보이는 기능만 구현하기(UsedBookView.vue)
    - [ ]  서버에서 실제 기능 api 구현하기(like.js_가제)
    - [ ] 클라이언트에서 해당 api 사용해서 온전하게 기능 구현하기

- 서재 데이터(좋아요한 책 및 중고 책 데이터) 불러오기 
    - [ ] TODO
    - [ ] TODO

- 상세보기 `api`호출
    - [x] `frontend` - isbn값에 의거한 데이터 요청
    - [x] `backend` - isbn값에 의거한 알라딘 `api`호출 및 해당 데이터를 `front`로 `send`처리
    - [ ] 베스트셀러 첫번째 카드 클릭시 isbn13값이 안와서 상세페이지에서 데이터호출이안됨

- 홈화면 CSS 관련 작업
    - [x] 베스트셀러 카테고리 버튼 활성화시 css처리
    - [x] 캐러셀

- 중고등록
    - [ ] 책검색 컴포넌트 수정
    - [ ] 중고 도서 등록 페이지 완성
    - [x] 중고 등록 db 저장
    - [x] 위도경도 메소드 사용(payment.vue)

- 중고 상세보기
    - [ ] 중고 db 불러오기 
    - [ ] 찜하기

- [ ] 상세페이지에서 검색하고 클릭시 화면 변경이 안됨
- [x] 리스트가 사라지게 하기
- [x] 검색어없으면 이동 못하게

- [ ] 유저가 아니면 중고도서 등록이 안되는 방안 추가
- [ ] 추천 검색어 박스 안사라짐 
- [ ] 상세보기 클릭시 화면 최상단 이동

**Comment by ssssssjay** [comment]
예외처리 없이 모든 케이스가 정상 작동임을 감안한 1차 구현입니다. 수정이 반드시 필요합니다.

**Comment by evelo0702** [comment]
책 상세 보기 api호출 잠시 보류해주세여~

**Comment by evelo0702** [comment]
책 상세보기 이동시 라우터에 책 아이디를 붙여서 드리는데 ex) http://localhost:5173/book/251552545
그걸 window.document.location.href 이거로 불러와서 split("/") 처리해서 책 아이디만 가져와서 bookNum에 넣어뒀습니다.  해당 변수를 활용해서 api호출하면될꺼같습니다~

**Comment by ssssssjay** [comment]
@evelo0702 혹시 어떤 파일에서 어떻게 처리하셨는지 알 수 있을까요?

**Comment by evelo0702** [comment]
내일 설명드릴께여

**Comment by ssssssjay** [comment]
그럼 제가 하고있던 관련작업은 잠시 멈추겠습니다:)
