### ISSUE TITLE
22.11.19 노영석 TODO

### ISSUE THREAD

**Issue by evelo0702** [BOOKPROJECT00/USED-BOOK#8]
베스트셀러 책 클릭시 상세화면  
검색 리스트 페이지네이션 
로그인정보 vuex 
채팅
db설계보완

===================================================================================
front 
- [x] 카카오 로그인시 db에 유저 데이터 등록 / 업데이트 - KakaoLogin.vue
- [x] 로그인 데이터 vuex에 저장 - KakaoLogin.vue + store/index.ts
- [x] 로그인 데이터 vue-cookies를 이용 시간지남에따라 데이터 휘발가능하게 적용 -store/ index.ts
- [x] 페이지네이션 컴포넌트 - Pagination.vue 
- [x] 검색 리스트 api 호출  - SearchView.vue
- [x] 검색 리스트 정렬 기능 구현  - SearchView.vue
- [x] 검색 리스트 페이지네이션 메소드 - SearchView.vue
- [x] 홈 베스트셀러 클릭시 책 상세보기로 책id값 전송 + 라우터 설정 -  HomeView.vue
- [x] 책 상세보기 페이지에서 라우터 주소값에서 책id값을 불러와서 bookNum 변수에 저장 - BookDetailView.vue 
- [ ] 채팅 db 설계 보완
- [ ] 채팅 vue로 설계 

back
- [x] 검색 리스트 페이지에서 정렬 기능을 위해 book.js 수정

요청사항 
홈에서 검색할때 추천 리스트 보여주는 개수 조절 필요
홈에서 검색해서 리스트 페이지로 이동할때 라우터에 검색어 연결 필요
